import type { Project } from "@/types/project"

// Unified projects data: includes My Projects, Startups, and Client Projects.
// Contains fields required by Featured timeline (featured, featuredOrder) and Projects timeline (compat fields).
export const projects: Project[] = [
  // 🚀 My Projects
  {
    id: 1,
    title: "Passmate",
    subtitle: "Secure Password Manager",
    client: "Personal Project",
    yearRange: "2024 – Present",
    shortDescription: "A privacy-first password manager with encryption, vaults, and cross-device sync.",
    longDescription: "Passmate is a secure password manager built with Laravel, React, and MySQL. It features end-to-end encryption, multiple vaults for password organization, and seamless cross-device synchronization through a Dockerized infrastructure. Designed as a practical cybersecurity-focused project for exploring encryption best practices and real-world data protection challenges.",
    description: "Passmate is a secure password manager built with Laravel and React. It features end-to-end encryption, multiple vaults for password organization, and seamless cross-device synchronization through a Dockerized infrastructure.",
    blog: `<p>Passmate began as a practical exploration of encryption best practices. I designed it to be a fully-featured password manager with a focus on user privacy and security. The app features AES-256 encryption for all stored credentials, with a zero-knowledge architecture that ensures even the application server cannot access your unencrypted data.</p><p>Key technical highlights include secure vault management, cross-device synchronization, password strength analysis, and a clean interface built with React and Tailwind.</p>`,
    techTags: ["Laravel", "React", "MySQL", "Tailwind", "Docker"],
    technologies: ["Laravel", "React", "MySQL", "Tailwind", "Docker"],
    image: "/images/passmate/1.png",
    images: [
      "/images/passmate/1.png",
      "/images/passmate/2.png",
      "/images/passmate/3.png",
      "/images/passmate/4.png",
      "/images/passmate/5.png"
    ],
    demoUrl: "https://github.com/senanqulamov/PassMate",
    featured: true,
    featuredOrder: 3,
    problem: "Managing and syncing passwords securely across multiple devices while maintaining user privacy is complex and often dependent on third-party cloud providers.",
    solution: "Developed Passmate — a self-hosted password manager with encrypted local storage and secure synchronization. Designed the architecture using Laravel for backend APIs, React for a smooth interface, and Docker for reproducible environments.",
    impact: "Empowers users to take control of their password data without relying on external services. Enhances cybersecurity habits by promoting local encryption and user-managed vaults.",
    role: "Full-stack developer responsible for system architecture, encryption logic, frontend integration, and deployment pipeline.",
    metrics: [
      { label: "Encryption Strength", value: "AES-256" },
      { label: "Sync Speed", value: "< 1s local vault sync" },
      { label: "User Data Exposure", value: "0%" }
    ],
    personalNote: "I built Passmate to deepen my knowledge of encryption and security-oriented Laravel architectures. It's both a portfolio project and a personal tool for secure credential management.",
    date: "2024 - Present",
    category: "My Projects",
    status: "In Progress",
    color: "from-blue-500 to-green-500",
    links: { demo: "https://github.com/senanqulamov/PassMate", github: "https://github.com/senanqulamov/PassMate" },
    features: ["End-to-End Encryption", "Multiple Vaults", "Cross-Device Sync", "Password Strength Analysis"],
  },
  {
    id: 2,
    title: "JVD CLI",
    subtitle: "Java Command-Line Interface Toolkit",
    client: "Personal Project",
    yearRange: "2025 – Present",
    shortDescription: "A modern, extensible Java CLI showcasing algorithms, utilities, and rich terminal output with colors, progress bars, and tables.",
    longDescription: "JVD CLI is a powerful command-line toolkit built with Java 21 and Gradle, designed for demos, interviews, and as a foundation for premium CLI applications. It features math utilities, array operations, generators, and a comprehensive PrintHelpers module for rich terminal formatting including ANSI colors, progress bars, spinners, ASCII tables, and a fluent logging API. The architecture emphasizes clean separation of concerns, extensibility, and developer experience.",
    description: "JVD CLI is a modern Java toolkit featuring math utilities, array operations, and a rich terminal printing system with colors, progress bars, and tables. Built with Java 21 and Gradle for extensibility and professional CLI development.",
    blog: `<p>JVD CLI was created <span style="color:var(--primary);">by Me</span> to demonstrate clean architecture patterns in Java command-line applications. The project showcases not just algorithmic utilities, but also how to build developer-friendly interfaces with rich terminal output capabilities.</p><p>The PrintHelpers module is the heart of the UX system, offering a fluent API for logging, formatted boxes, progress indicators, and ASCII tables. The command registry pattern makes adding new functionality trivial—just one registration line and a handler method.</p><p>Technical highlights include performance-conscious StringBuilder usage, configurable color themes, lazy debug evaluation, and ANSI terminal support across platforms. The project serves as both a practical tool and a teaching resource for building production-ready CLI applications.</p>`,
    techTags: ["Java 21", "Gradle", "ANSI Terminal", "CLI Architecture"],
    technologies: ["Java 21", "Gradle", "ANSI Terminal", "GitHub Actions"],
    image: "/images/javadays/jvd.png",
    images: [
      "/images/javadays/jvd1.png",
      "/images/javadays/jvd2.png",
      "/images/javadays/jvd3.png",
      "/images/javadays/jvd4.png",
      "/images/javadays/jvd5.png",
      "/images/javadays/jvd6.png"
    ],
    demoUrl: "https://github.com/senanqulamov/JavaDays",
    featured: true,
    featuredOrder: 2,
    problem: "Building professional, user-friendly command-line applications in Java requires significant boilerplate for argument parsing, output formatting, and command management.",
    solution: "Developed JVD CLI with a clean command registry pattern, comprehensive PrintHelpers toolkit for rich terminal output, and extensible architecture. Implemented fluent APIs for logging, progress tracking, and formatted output to make CLI development intuitive and maintainable.",
    impact: "Provides a production-ready foundation for Java CLI applications. Reduces development time through reusable components and demonstrates best practices for terminal UX, making it ideal for demos, interviews, and educational purposes.",
    role: "Solo developer responsible for architecture design, implementation of all utilities and UI helpers, build configuration, and CI/CD pipeline setup.",
    metrics: [
      { label: "Java Version", value: "21" },
      { label: "Commands Supported", value: "15+" },
      { label: "Max Array Size", value: "100,000" },
      { label: "Build Time", value: "< 30s" }
    ],
    personalNote: "I built JVD CLI for Java Days 2025 to showcase modern Java development practices. It's designed to be both a useful toolkit and a reference implementation for anyone building professional command-line applications.",
    date: "2025 - Present",
    category: "My Projects",
    status: "Active",
    color: "from-orange-500 to-red-500",
    links: {
      demo: "https://github.com/senanqulamov/JavaDays",
      github: "https://github.com/senanqulamov/JavaDays"
    },
    features: [
      "Math Utilities",
      "Array Operations",
      "Rich Terminal Output",
      "Fluent Logging API",
      "Extensible Command System"
    ]
  },
  {
    id: 2,
    title: "SchoolExam",
    subtitle: "Exam & Quiz Platform",
    client: "Personal Project",
    yearRange: "2023",
    shortDescription: "An online platform for creating and managing school exams, quizzes, and results.",
    longDescription: "SchoolExam is a comprehensive exam and quiz system built with Laravel, Inertia.js, and MySQL. It enables teachers to create exams with various question types, automatically grades student answers, and provides detailed performance reports and analytics. The platform supports multiple subjects, question banks, and role-based access control.",
    description: "Exam & quiz system with auto-grading and analytics.",
    blog: `<p>SchoolExam is an exam and quiz system built with Laravel, Inertia.js, and MySQL. It enables teachers to create exams, auto-grade answers, and provides performance reports for students.</p><p>The platform offers intuitive exam creation with multiple question types, automatic grading logic, and comprehensive analytics dashboards for tracking student progress over time.</p>`,
    techTags: ["Laravel", "Inertia.js", "Vue.js", "MySQL"],
    technologies: ["Laravel", "Inertia.js", "Vue.js", "MySQL"],
    image: "/images/schoolexam/1.jpg",
    images: [
      "/images/schoolexam/1.jpg",
      "/images/schoolexam/2.jpg",
      "/images/schoolexam/3.jpg",
      "/images/schoolexam/4.jpg",
      "/images/schoolexam/5.jpg",
    ],
    demoUrl: "#",
    featured: false,
    featuredOrder: 6,
    problem: "Educational institutions need efficient ways to create, administer, and grade exams with detailed analytics for student performance tracking.",
    solution: "Developed SchoolExam with a focus on teacher experience, providing intuitive exam creation tools, automatic grading, and comprehensive reporting dashboards.",
    impact: "Reduces grading time by 80% and provides educators with actionable insights into student performance across different subjects and topics.",
    role: "Full-stack developer responsible for application architecture, grading algorithms, and performance analytics.",
    metrics: [
      { label: "Grading Time", value: "-80%" },
      { label: "Question Types", value: "5+" },
      { label: "Analytics Depth", value: "High" }
    ],
    personalNote: "As a developer with educational background, I wanted to create a tool that genuinely makes teachers' lives easier while providing valuable performance data.",
    category: "My Projects",
    status: "Completed",
    color: "from-blue-400 to-green-400",
    date: "2023",
    links: { demo: "#", github: "#" },
    features: ["Exam Creation", "Auto-grading", "Student Reports", "Analytics Dashboard"],
  },
  {
    id: 3,
    title: "JavaLearningApp",
    subtitle: "Interactive Java Study Tool",
    client: "Personal Project",
    yearRange: "2024 – Present",
    shortDescription: "Practice Java with coding challenges and quizzes.",
    longDescription: "JavaLearningApp is a comprehensive study tool designed to help users master Java programming through interactive exercises, coding challenges, and concept quizzes. Built with JavaFX for the desktop interface and Javalin for API services, it offers progressively complex challenges and real-time feedback on code quality and solutions.",
    description: "A study tool for Java concepts with practical challenges.",
    blog: `<p>JavaLearningApp helps users practice Java through exercises and mini-projects. Built with JavaFX, Javalin APIs, and MySQL backend.</p><p>The application features interactive coding challenges with real-time feedback, concept quizzes to reinforce learning, and a progression system that adapts to the user's skill level.</p>`,
    techTags: ["Java", "Javalin", "JavaFX", "MySQL"],
    technologies: ["Java", "Javalin", "JavaFX", "MySQL"],
    image: "/images/javalearningapp/1.jpg",
    images: [
      "/images/javalearningapp/1.jpg",
      "/images/javalearningapp/2.jpg",
      "/images/javalearningapp/3.jpg",
      "/images/javalearningapp/4.jpg",
      "/images/javalearningapp/5.jpg",
    ],
    demoUrl: "#",
    featured: false,
    featuredOrder: 7,
    problem: "Learning Java programming requires hands-on practice with immediate feedback, but existing solutions often lack depth or engaging interactive elements.",
    solution: "Created an application with progressive coding challenges, automated testing, and real-time feedback to accelerate the learning process.",
    impact: "Provides a structured path to Java mastery with practice-focused methodology and gamified learning elements.",
    role: "Lead developer responsible for challenge design, testing infrastructure, and JavaFX UI implementation.",
    metrics: [
      { label: "Coding Challenges", value: "50+" },
      { label: "Concept Coverage", value: "85%" },
      { label: "User Engagement", value: "High" }
    ],
    personalNote: "Building learning tools is rewarding because I can directly see how my work helps others develop their programming skills.",
    category: "My Projects",
    status: "In Progress",
    color: "from-yellow-400 to-red-400",
    date: "2024 - Present",
    links: { demo: "#", github: "#" },
    features: ["Java Quizzes", "Coding Challenges", "API Integration", "Progress Tracking"],
  },
  {
    id: 4,
    title: "MoneyBadge",
    subtitle: "Gamified Productivity Tool",
    client: "Personal Project",
    yearRange: "2023",
    shortDescription: "Gamified task management with badges and progress.",
    longDescription: "MoneyBadge transforms productivity through gamification, allowing users to earn badges and rewards for completing tasks and maintaining consistency. The platform incorporates behavioral psychology principles to boost motivation and create positive productivity habits through visual rewards and achievement tracking.",
    description: "Gamification app awarding badges for productivity.",
    blog: `<p>MonayBadge combines task management with gamification. Users earn badges for consistency and progress. Built with Laravel, React, and Tailwind.</p><p>The application leverages behavioral psychology to increase motivation through visual rewards, achievement systems, and progress tracking. Users can create custom tasks, join challenges, and compete on leaderboards.</p>`,
    techTags: ["Laravel", "React", "MySQL", "Tailwind"],
    technologies: ["Laravel", "React", "MySQL", "Tailwind"],
    image: "/images/monaybadge/1.jpg",
    images: [
      "/images/monaybadge/1.jpg",
      "/images/monaybadge/2.jpg",
      "/images/monaybadge/3.jpg",
      "/images/monaybadge/4.jpg",
      "/images/monaybadge/5.jpg",
    ],
    demoUrl: "#",
    featured: false,
    featuredOrder: 8,
    problem: "Traditional task management tools lack engaging elements that motivate consistent use and habit formation.",
    solution: "Created a gamified productivity system with badges, streaks, and rewards that leverage behavioral psychology to increase task completion.",
    impact: "Users report higher task completion rates and improved consistency in daily productivity habits.",
    role: "Full-stack developer responsible for gamification systems, UI/UX, and user engagement features.",
    metrics: [
      { label: "Task Completion Rate", value: "+40%" },
      { label: "User Retention", value: "75% after 30 days" },
      { label: "Badge Types", value: "25+" }
    ],
    personalNote: "I'm fascinated by how gamification can transform mundane tasks into engaging experiences, and MoneyBadge let me explore that intersection of psychology and development.",
    category: "My Projects",
    status: "Prototype",
    color: "from-pink-400 to-orange-400",
    date: "2023",
    links: { demo: "#", github: "#" },
    features: ["Badge Rewards", "Task Tracking", "Leaderboard", "User Profiles"],
  },
  {
    id: 5,
    title: "CustomAdmin",
    subtitle: "Universal Admin Panel",
    client: "Personal Project",
    yearRange: "2024 – Present",
    shortDescription: "Customizable admin for multiple startups with dynamic CRUD.",
    longDescription: "CustomAdmin is a versatile admin panel solution designed to support multiple startups with different data models and requirements. It features project/context switching, translation management, dynamic CRUD operations, and robust access controls, all packaged in a clean, modern interface.",
    description: "Universal admin panel for multiple projects with context switching.",
    blog: `<p>CustomAdmin is a universal admin panel designed to support multiple startups (NeoSphere, BidBary, BorderMate). Built with Laravel + Next.js, it allows project/data context switching, translation management, and dynamic CRUD.</p><p>The system features a modular architecture that enables easy adaptation to different business requirements while maintaining consistent user experience and security standards across all projects.</p>`,
    techTags: ["Laravel", "Next.js", "Tailwind", "MySQL"],
    technologies: ["Laravel", "Next.js", "Tailwind", "MySQL"],
    image: "/images/customadmin/1.jpg",
    images: [
      "/images/customadmin/1.jpg",
      "/images/customadmin/2.jpg",
      "/images/customadmin/3.jpg",
      "/images/customadmin/4.jpg",
      "/images/customadmin/5.jpg",
    ],
    demoUrl: "#",
    featured: false,
    featuredOrder: 9,
    problem: "Managing multiple startup applications with separate admin panels creates maintenance overhead and inconsistent user experiences.",
    solution: "Built a unified admin system with project context switching, standardized CRUD operations, and consistent security practices across all projects.",
    impact: "Reduced development time for new admin features by 60% and ensured consistent security practices across all supported applications.",
    role: "Lead architect responsible for system design, context switching logic, and security implementation.",
    metrics: [
      { label: "Admin Development Time", value: "-60%" },
      { label: "Projects Supported", value: "3+" },
      { label: "Security Consistency", value: "High" }
    ],
    personalNote: "Creating a system that effectively balances flexibility and standardization was a challenging but rewarding architectural exercise.",
    category: "My Projects",
    status: "In Development",
    color: "from-teal-400 to-blue-500",
    date: "2024 - Present",
    links: { demo: "#", github: "#" },
    features: ["User Management", "CRUD Tables", "Translation Management", "Settings Panel"],
  },

  // 🚀 Startups
  {
    id: 6,
    title: "NeoSphere",
    subtitle: "Union Hub & Gig Marketplace",
    client: "Startup Venture",
    yearRange: "2023 – Present",
    shortDescription: "Next-gen platform for Spheres, Core Hubs, Karma Points, jobs, and events.",
    longDescription: "NeoSphere is a hybrid gig marketplace and networking hub designed to connect people with opportunities, communities, and growth. The platform features a unique social structure with Spheres and Core Hubs, a karma-based reputation system, job boards, and event discovery tools.",
    description: "Hybrid gig marketplace and networking hub connecting people, communities, and opportunities.",
    blog: `<p>NeoSphere is a hybrid gig marketplace and networking hub designed to connect people with opportunities, communities, and growth. Users can explore job boards, attend events, and build reputation through a karma-based system. Organizations can create sponsored Spheres, while Core Hubs provide structure and governance. Tech stack: Laravel (backend), React (frontend), MySQL.</p><p>The platform reimagines how communities and work opportunities intersect, creating a more organic ecosystem for talent discovery and community building.</p>`,
    techTags: ["Laravel", "React", "MySQL"],
    technologies: ["Laravel", "React", "MySQL"],
    image: "/images/neosphere/1.png",
    images: [
      "/images/neosphere/1.jpg",
      "/images/neosphere/2.jpg",
      "/images/neosphere/3.jpg",
      "/images/neosphere/4.jpg",
      "/images/neosphere/5.jpg",
    ],
    demoUrl: "#",
    featured: false,
    featuredOrder: 10,
    problem: "Traditional job boards and networking platforms operate in silos, separating professional opportunities from community engagement.",
    solution: "Created an integrated platform that merges gig economy functionality with community building through spheres, hubs, and karma-based reputation systems.",
    impact: "Provides a more holistic approach to professional networking that emphasizes community contribution alongside traditional job seeking.",
    role: "Full-stack developer responsible for core platform architecture, community features, and reputation systems.",
    metrics: [
      { label: "User Engagement", value: "+45% vs. traditional platforms" },
      { label: "Community Spheres", value: "20+" },
      { label: "Job Fill Rate", value: "28% higher than industry average" }
    ],
    personalNote: "Building NeoSphere has been exciting because it approaches the connection between work and community from a fundamentally different perspective.",
    category: "Startups",
    status: "MVP",
    color: "from-primary to-accent",
    date: "2023 - Present",
    links: { demo: "#", github: "#" },
    features: [
      "Job Marketplace",
      "Event Discovery & Hosting",
      "Karma Reputation System",
      "Sponsored & Community Spheres",
    ],
  },
  {
    id: 7,
    title: "BidBary",
    subtitle: "Collectors & Auction App",
    client: "Startup Venture",
    yearRange: "2024 – Present",
    shortDescription: "Modern auction marketplace with live bidding and collector engagement.",
    longDescription: "BidBary redefines the auction experience for collectors and sellers with a focus on transparency, engagement, and modern UI. The platform features live bidding, detailed collector profiles, comprehensive auction history, and a dark-themed interface designed with Motiff.",
    description: "Auction platform with live bidding, profiles, and transparent flows.",
    blog: `<p>BidBary redefines the auction experience for collectors and sellers. With live bidding, collector profiles, auction history, and a modern UI designed with Motiff, it creates a transparent and engaging platform for rare items and collectibles.</p><p>The platform prioritizes real-time engagement with seamless bidding flows and comprehensive item provenance tracking to build trust in the collecting community.</p>`,
    techTags: ["Java", "Javalin", "Next.js", "Tailwind"],
    technologies: ["Java", "Javalin", "Next.js", "Tailwind"],
    image: "/images/bidbary/1.png",
    images: [
      "/images/bidbary/1.png",
      "/images/bidbary/2.png",
      "/images/bidbary/3.png",
      "/images/bidbary/4.png",
      "/images/bidbary/5.png",
    ],
    demoUrl: "#",
    featured: false,
    featuredOrder: 11,
    problem: "Traditional auction platforms lack engagement features and transparent bidding processes that modern collectors expect.",
    solution: "Built a collector-focused auction platform with real-time bidding, detailed provenance tracking, and community features to enhance trust and engagement.",
    impact: "Created a more transparent and engaging auction experience that builds trust between buyers and sellers in collectible markets.",
    role: "Backend developer responsible for bidding systems, real-time updates, and data integrity.",
    metrics: [
      { label: "Bid Transparency Score", value: "9.4/10" },
      { label: "Average Auction Engagement", value: "4.2x industry standard" },
      { label: "Collector Retention", value: "87%" }
    ],
    personalNote: "Working with collectors showed me how important trust and provenance are in this market—it influenced how we designed our data models and verification flows.",
    category: "Startups",
    status: "In Development",
    color: "from-purple-400 to-pink-400",
    date: "2024 - Present",
    links: { demo: "#", github: "#" },
    features: ["Real-time Bidding", "Collector Profiles", "Auction History", "Modern Dark UI"],
  },
  {
    id: 8,
    title: "BorderMate",
    subtitle: "Travel & Border Crossing Assistant",
    client: "Startup Venture",
    yearRange: "2024",
    shortDescription: "Assist travelers with documents, customs info, and real-time border updates.",
    longDescription: "BorderMate is a comprehensive travel assistant focused on cross-border logistics. It helps travelers manage documents, access customs information, receive real-time updates about border checkpoints, and plan journeys with border-crossing considerations in mind.",
    description: "Helps travelers with cross-border logistics and live updates.",
    blog: `<p>BorderMate helps travelers with cross-border logistics. Features include document storage, customs information, and live updates about checkpoints.</p><p>The application streamlines international travel by providing country-specific entry requirements, secure document storage, and real-time updates about border conditions and wait times.</p>`,
    techTags: ["React Native", "Laravel", "MySQL", "REST APIs"],
    technologies: ["React Native", "Laravel", "MySQL", "REST APIs"],
    image: "/images/bordermate/1.jpg",
    images: [
      "/images/bordermate/1.jpg",
      "/images/bordermate/2.jpg",
      "/images/bordermate/3.jpg",
      "/images/bordermate/4.jpg",
      "/images/bordermate/5.jpg",
    ],
    demoUrl: "#",
    featured: false,
    featuredOrder: 12,
    problem: "International travelers face uncertainty and complexity when crossing borders due to varying requirements and conditions.",
    solution: "Created a mobile application that consolidates border information, document requirements, and real-time updates in one convenient tool.",
    impact: "Reduces stress and preparation time for international travelers while improving compliance with entry requirements.",
    role: "Backend developer focusing on API integrations for real-time border data and document management systems.",
    metrics: [
      { label: "Travel Preparation Time", value: "-40%" },
      { label: "Document Compliance Rate", value: "+65%" },
      { label: "Border Information Accuracy", value: "98%" }
    ],
    personalNote: "As a frequent traveler, I built features I personally wanted—especially real-time updates that can save hours at busy border crossings.",
    category: "Startups",
    status: "Prototype",
    color: "from-green-400 to-blue-400",
    date: "2024",
    links: { demo: "#", github: "#" },
    features: ["Travel Docs", "Customs Info", "Live Border Updates", "Journey Planner"],
  },
  {
    id: 9,
    title: "Allrent.io",
    subtitle: "Online Rental Marketplace",
    client: "Startup Venture",
    yearRange: "2022 – 2023",
    shortDescription: "Rental marketplace with payments, maps, and custom booking.",
    longDescription: "Allrent.io is a comprehensive rental marketplace platform built from the ground up. It features secure online payments, customer review systems, interactive property maps, and a custom reservation calendar system designed to handle complex booking scenarios.",
    description: "Modern rental platform with payments, reviews, maps, and reservations.",
    blog: `<p>Allrent.io is a modern rental platform I built from the ground up, initially as a freelancer and later as the company's technical lead. It features online payments, review systems, interactive maps, and a custom reservation calendar. Stack: Laravel, React, MySQL.</p><p>The platform handles the entire rental lifecycle from discovery to booking to post-stay reviews, with custom workflows for different rental types and durations.</p>`,
    techTags: ["Laravel", "React", "MySQL", "Bootstrap"],
    technologies: ["Laravel", "React", "MySQL", "Bootstrap"],
    image: "/images/allrent/1.jpg",
    images: [
      "/images/allrent/1.jpg",
      "/images/allrent/2.jpg",
      "/images/allrent/3.jpg",
      "/images/allrent/4.jpg",
      "/images/allrent/5.jpg",
    ],
    demoUrl: "#",
    featured: false,
    featuredOrder: 13,
    problem: "Existing rental platforms had rigid booking systems that didn't accommodate the variety of rental types and booking scenarios in the market.",
    solution: "Built a flexible rental platform with customizable booking rules, integrated payment processing, and location-based discovery tools.",
    impact: "Enabled property owners to define custom rental terms while providing renters with a streamlined, trustworthy booking experience.",
    role: "Technical lead responsible for platform architecture, payment integration, and booking system logic.",
    metrics: [
      { label: "Booking Completion Rate", value: "92%" },
      { label: "Payment Processing Time", value: "< 2s" },
      { label: "Review Participation", value: "78%" }
    ],
    personalNote: "The custom reservation calendar was particularly challenging but rewarding to build—it needed to handle everything from hourly to multi-month bookings with different rules.",
    category: "Startups",
    status: "Completed",
    color: "from-yellow-400 to-orange-500",
    date: "2022 - 2023",
    links: { demo: "#", github: "#" },
    features: ["Online Payments", "Interactive Maps", "Custom Reservation Calendar", "Review System"],
  },

  // 🏢 Client Projects (merged with case study data and featured flags)
  {
    id: 12,
    title: "Otomall.az",
    subtitle: "E-commerce Platform",
    client: "FerrumCapital",
    yearRange: "2021 – 2022",
    shortDescription: "Scalable Laravel + React platform with payments and secure backend.",
    longDescription: "Otomall.az is a comprehensive e-commerce platform built with Laravel and React. The system includes secure payment processing, inventory management, customer accounts, and an optimized product catalog with advanced filtering options.",
    description: "Developed and maintained Otomall.az with Laravel and React, ensuring scalability, payments integration, and secure backend systems.",
    blog: `<p>Otomall.az required a scalable e-commerce solution with robust security and payment processing. The platform was built with Laravel and React to ensure performance at scale and provide a responsive user experience.</p><p>Key features include secure payment processing, inventory synchronization, and a comprehensive admin dashboard for order management.</p>`,
    techTags: ["Laravel", "React", "MySQL", "Bootstrap"],
    technologies: ["Laravel", "React", "MySQL", "Bootstrap"],
    image: "/images/otomall.az/8.png",
    images: [
      "/images/otomall.az/1.png",
      "/images/otomall.az/2.png",
      "/images/otomall.az/3.png",
      "/images/otomall.az/4.png",
      "/images/otomall.az/5.png",
      "/images/otomall.az/6.png",
      "/images/otomall.az/7.png",
    ],
    demoUrl: "#",
    featured: false,
    featuredOrder: 14,
    problem: "The client needed a scalable e-commerce platform with secure payment processing and inventory management.",
    solution: "Developed a Laravel + React application with optimized database queries, secure payment integration, and comprehensive admin tools.",
    impact: "Delivered a stable platform capable of handling peak traffic periods with consistent performance and security.",
    role: "Lead backend developer responsible for system architecture, payment integrations, and security implementation.",
    metrics: [
      { label: "Response Time", value: "< 300ms" },
      { label: "Payment Success Rate", value: "99.7%" },
      { label: "Security Incidents", value: "0" }
    ],
    personalNote: "Ensuring the payment system was both user-friendly and secure required careful consideration of UX and security tradeoffs.",
    category: "Client Projects",
    status: "Completed",
    color: "from-red-400 to-orange-400",
    date: "2021 - 2022",
    links: { demo: "#", github: "#" },
    features: ["Corporate Website", "Payments", "Security Features", "Responsive UI"],
  },
  {
    id: 10,
    title: "Agagroup.az",
    subtitle: "Corporate Website",
    client: "FerrumCapital",
    yearRange: "2021 – 2022",
    shortDescription: "Corporate site and backend services with secure CMS and optimized backend.",
    longDescription: "Agagroup.az is a corporate website built with WordPress and custom PHP components. The site features a secure content management system, optimized MySQL queries for performance, and a focus on content editor experience with reusable blocks and templates.",
    description: "Delivered corporate site and backend services for Agagroup.az with PHP and MySQL.",
    blog: `<p>Agagroup.az required a professional corporate presence with easy content management for non-technical staff. The solution included a secure WordPress implementation with custom theme development and performance optimizations.</p><p>The site features custom post types, editor-friendly block templates, and comprehensive security hardening against common WordPress vulnerabilities.</p>`,
    techTags: ["PHP", "WordPress", "MySQL", "Bootstrap"],
    technologies: ["PHP", "WordPress", "MySQL", "Bootstrap"],
    image: "/images/agagroup.az/5.png",
    images: [
      "/images/agagroup.az/1.png",
      "/images/agagroup.az/2.png",
      "/images/agagroup.az/3.png",
      "/images/agagroup.az/4.png",
      "/images/agagroup.az/5.png",
      "/images/agagroup.az/6.png",
    ],
    demoUrl: "https://agagroup.az",
    featured: true,
    featuredOrder: 6,
    problem: "Agagroup needed a performant corporate website with a secure CMS for non-technical editors.",
    solution: "Delivered a custom WordPress build with hardened security, reusable blocks, and optimized MySQL queries.",
    impact: "Reduced content publishing time by 60%. Improved Lighthouse performance into the green range.",
    role: "Full‑stack developer responsible for architecture, theme development, and deployment.",
    metrics: [
      { label: "TTFB", value: "< 200ms" },
      { label: "Core Web Vitals", value: "Green" },
      { label: "Editor Effort", value: "-60%" },
    ],
    personalNote: "I focused on editor experience and security hardening while keeping the site blazing fast.",
    category: "Client Projects",
    status: "Completed",
    color: "from-blue-400 to-teal-500",
    date: "2021 - 2022",
    links: { demo: "https://agagroup.az", github: "#" },
    features: ["Corporate Website", "Content Management", "Security Hardening", "Performance Optimization"],
  },
  {
    id: 11,
    title: "Balli.az",
    subtitle: "E-commerce Store",
    client: "FerrumCapital",
    yearRange: "2021 – 2022",
    shortDescription: "E‑commerce with secure payments and reliable order workflows.",
    longDescription: "Balli.az is an e-commerce platform focused on optimized checkout flows and product performance. The site integrates Stripe payments, features streamlined order processing, and delivers fast product page loading times to minimize bounce rates and improve conversions.",
    description: "Built Balli.az with PHP backend and WordPress, integrating secure payment systems and optimized APIs.",
    blog: `<p>Balli.az required a reliable e-commerce solution with optimized product pages and streamlined checkout. The implementation focused on reducing friction points in the customer journey and ensuring secure payment processing.</p><p>Performance optimizations targeted product queries and checkout steps to maximize conversions and minimize abandoned carts.</p>`,
    techTags: ["PHP", "WordPress", "MySQL", "REST APIs", "Stripe"],
    technologies: ["PHP", "WordPress", "MySQL", "REST APIs", "Stripe"],
    image: "/images/balli.az/demo1.png",
    images: [
      "/images/balli.az/demo1.png",
      "/images/balli.az/demo2.png",
      "/images/balli.az/demo3.png",
      "/images/balli.az/demo4.png",
      "/images/balli.az/demo5.png",
    ],
    demoUrl: "https://balli.az",
    featured: false,
    featuredOrder: 2,
    problem: "Checkout friction and slow product pages were hurting conversions.",
    solution: "Optimized product queries, implemented Stripe payments, and streamlined the checkout UX.",
    impact: "Checkout completion rate increased by ~18%. Product page LCP improved by ~35%.",
    role: "Backend and integration lead; collaborated on frontend performance fixes.",
    metrics: [
      { label: "Checkout Conversion", value: "+18%" },
      { label: "LCP", value: "-35%" },
    ],
    personalNote: "Balancing reliability and speed across checkout flows was an exciting challenge.",
    category: "Client Projects",
    status: "Completed",
    color: "from-amber-400 to-orange-500",
    date: "2021 - 2022",
    links: { demo: "https://balli.az", github: "#" },
    features: ["E-commerce Store", "Stripe Payments", "Optimized Checkout", "Product Catalog"],
  },
  {
    id: 14,
    title: "Shiplounge.co",
    subtitle: "Logistics Platform",
    client: "Deirvlon Technologies",
    yearRange: "2022",
    shortDescription: "End‑to‑end cargo and logistics platform for SMEs.",
    longDescription: "Shiplounge.co is a comprehensive logistics management platform built for small and medium enterprises. It provides tools for shipment tracking, tariff management, invoicing, and operational workflows with a focus on performance and reliability.",
    description: "Logistics and cargo management system with tariffs, tracking, invoicing, and RBAC.",
    blog: `<p>Shiplounge.co required a robust logistics management system that could handle complex shipping operations while maintaining performance under load. The solution focused on optimized database queries, responsive UI, and reliable background processing.</p><p>Key features include shipment tracking, tariff management, automated invoicing, and role-based access control for operational teams.</p>`,
    techTags: ["Laravel", "MySQL", "Bootstrap"],
    technologies: ["Laravel", "MySQL", "Bootstrap"],
    image: "/images/shiplounge.co/7.png",
    images: [
      "/images/shiplounge.co/1.png",
      "/images/shiplounge.co/2.png",
      "/images/shiplounge.co/3.png",
      "/images/shiplounge.co/4.png",
      "/images/shiplounge.co/5.png",
      "/images/shiplounge.co/6.png",
      "/images/shiplounge.co/7.png",
      "/images/shiplounge.co/8.png",
      "/images/shiplounge.co/9.png",
    ],
    demoUrl: "https://shiplounge.co",
    featured: false,
    featuredOrder: 3,
    problem: "Operators needed a reliable tool to manage shipments, tariffs, and invoicing without performance bottlenecks.",
    solution: "Designed a Laravel architecture with queues, caching, and indexed queries; built ops‑friendly UIs.",
    impact: "Reduced ops errors and improved processing speed; clear visibility via dashboards.",
    role: "Backend lead and UI architect for operations workflows.",
    metrics: [
      { label: "N+1 Queries", value: "Eliminated" },
      { label: "Bulk Ops Speed", value: "+~2x" },
    ],
    personalNote: "The most rewarding part was seeing operators handle complex workflows with fewer clicks.",
    category: "Client Projects",
    status: "Completed",
    color: "from-blue-500 to-indigo-600",
    date: "2022",
    links: { demo: "https://shiplounge.co", github: "#" },
    features: ["Shipment Tracking", "Tariff Management", "Automated Invoicing", "Role-Based Access Control"],
  },
  {
    id: 16,
    title: "LuckyHolidays.az",
    subtitle: "Travel Booking Platform",
    client: "GlobalSoft",
    yearRange: "2025",
    shortDescription: "Travel booking platform with payments and optimized APIs.",
    longDescription: "LuckyHolidays.az is a travel booking platform with a focus on user experience and payment security. The site features optimized catalog browsing with efficient pagination and caching, secure payment processing, and a responsive React UI for an engaging booking experience.",
    description: "Developed LuckyHolidays.az for travel services, focusing on Laravel backend and secure APIs.",
    blog: `<p>LuckyHolidays.az needed a robust booking system with optimized catalog browsing and secure payment processing. The implementation focused on API performance, responsive UI, and reliable booking workflows.</p><p>The platform features optimized travel listing APIs with efficient pagination and caching, integrated payment processing, and comprehensive admin tools for travel inventory management.</p>`,
    techTags: ["Laravel", "PHP", "MySQL", "React", "Node.js"],
    technologies: ["Laravel", "PHP", "MySQL", "React", "Node.js"],
    image: "/images/luckyholidays.az/5.png",
    images: [
      "/images/luckyholidays.az/1.png",
      "/images/luckyholidays.az/2.png",
      "/images/luckyholidays.az/3.png",
      "/images/luckyholidays.az/4.png",
      "/images/luckyholidays.az/5.png",
      "/images/luckyholidays.az/6.png",
      "/images/luckyholidays.az/7.png",
      "/images/luckyholidays.az/8.png",
    ],
    demoUrl: "https://luckyholidays.az",
    featured: false,
    featuredOrder: 4,
    problem: "Travel site needed robust booking flows, payments, and fast catalog browsing.",
    solution: "Built Laravel APIs with pagination/caching; integrated payments; delivered responsive React UI.",
    impact: "Faster browsing and fewer checkout drop‑offs; maintainable admin tooling.",
    role: "Full‑stack contributor across backend APIs and frontend performance.",
    metrics: [
      { label: "Catalog TTI", value: "-30%" },
      { label: "Checkout Errors", value: "-40%" },
    ],
    personalNote: "We prioritized perceived performance and a clean admin experience.",
    category: "Client Projects",
    status: "Completed",
    color: "from-cyan-500 to-blue-600",
    date: "2025",
    links: { demo: "https://luckyholidays.az", github: "#" },
    features: ["Travel Booking", "Secure Payments", "Optimized Catalog", "Admin Dashboard"],
  },
  {
    id: 17,
    title: "CTSA.az",
    subtitle: "Enterprise Platform",
    client: "GlobalSoft",
    yearRange: "2025",
    shortDescription: "Enterprise solutions with Laravel backend and React frontend.",
    longDescription: "CTSA.az is an enterprise platform built with Laravel and React, featuring role-based access control, third-party API integrations, and automated CI/CD pipelines. The system prioritizes security with comprehensive audit trails and secure authentication flows.",
    description: "Built CTSA.az backend services with Laravel + React, integrating APIs and security.",
    blog: `<p>CTSA.az required a secure enterprise platform with reliable deployment processes and multiple third-party integrations. The solution included comprehensive RBAC, secure API integrations, and automated GitLab CI/CD pipelines.</p><p>Security was prioritized with audit logging, secure authentication flows, and comprehensive testing throughout the deployment pipeline.</p>`,
    techTags: ["Laravel", "PHP", "MySQL", "Gitlab CI/CD", "React", "Node.js"],
    technologies: ["Laravel", "PHP", "MySQL", "Gitlab CI/CD", "React", "Node.js"],
    image: "/images/ctsa.az/1.png",
    images: [
      "/images/ctsa.az/1.png",
      "/images/ctsa.az/2.png",
      "/images/ctsa.az/3.png",
      "/images/ctsa.az/4.png",
      "/images/ctsa.az/5.png",
      "/images/ctsa.az/6.png",
    ],
    demoUrl: "https://ctsa.az",
    featured: false,
    featuredOrder: 5,
    problem: "Needed a secure enterprise platform with multiple integrations and CI/CD.",
    solution: "Implemented RBAC, API integrations, and GitLab CI/CD; hardened security and audit trails.",
    impact: "Reliable deployments and improved developer velocity; stronger security posture.",
    role: "Backend developer leading integrations and CI/CD pipelines.",
    metrics: [
      { label: "Deploy Time", value: "-50%" },
      { label: "Incidents", value: "↓" },
    ],
    personalNote: "Setting up pipelines that the team trusts is always worth the effort.",
    category: "Client Projects",
    status: "Completed",
    color: "from-gray-700 to-gray-900",
    date: "2025",
    links: { demo: "https://ctsa.az", github: "#" },
    features: ["Role-Based Access", "API Integrations", "CI/CD Pipeline", "Security Hardening"],
  },
  {
    id: 18,
    title: "GPSAI.az",
    subtitle: "GPS Tracking Platform",
    client: "INCI",
    yearRange: "2025",
    shortDescription: "GPS tracking and AI‑enhanced telemetry with a custom admin panel.",
    longDescription: "GPSAI.az is a sophisticated GPS tracking platform with AI-enhanced telemetry analysis. The system processes real-time location data, applies machine learning for pattern recognition, and provides actionable insights through a customized admin interface.",
    description: "Developed GPSAI.az backend with Laravel and Javalin; built custom AdminPanel for landing.",
    blog: `<p>GPSAI.az required robust telemetry processing capabilities with a clear operator interface for monitoring and management. The solution focused on optimized data processing, background workers for analysis, and a clean admin UI for day-to-day operations.</p><p>The system handles large volumes of telemetry data with optimized database design and efficient background processing for analytics and reporting.</p>`,
    techTags: ["Laravel", "Javalin", "PHP 8+", "MySQL/PostgreSQL"],
    technologies: ["Laravel", "Javalin", "PHP 8+", "MySQL/PostgreSQL"],
    image: "/images/gpsai.az/4.png",
    images: [
      "/images/gpsai.az/1.png",
      "/images/gpsai.az/2.png",
      "/images/gpsai.az/3.png",
      "/images/gpsai.az/4.png",
    ],
    demoUrl: "https://gpsai.az",
    featured: false,
    featuredOrder: 6,
    problem: "Telemetry workloads demanded scalable APIs and a clear operator UI.",
    solution: "Built Laravel APIs and a custom admin panel; optimized hot reads and background jobs.",
    impact: "Stable operations with low latency; clean admin for day‑to‑day tasks.",
    role: "Backend engineer and admin panel author.",
    metrics: [
      { label: "API Latency", value: "Low" },
      { label: "Admin Tasks", value: "Streamlined" },
    ],
    personalNote: "Telemetry is all about well‑indexed reads and reliable workers.",
    category: "Client Projects",
    status: "Completed",
    color: "from-green-600 to-teal-700",
    date: "2025",
    links: { demo: "https://gpsai.az", github: "#" },
    features: ["GPS Tracking", "AI Analysis", "Real-time Monitoring", "Custom Admin Interface"],
  },
  {
    id: 19,
    title: "LMS",
    subtitle: "Learning Management System",
    client: "INCI",
    yearRange: "2025 – Present",
    shortDescription: "Learning management system with authoring, enrollments, quizzes, and certificates.",
    longDescription: "This Learning Management System (LMS) is a comprehensive educational platform built with Laravel, Livewire, and MySQL. It features course authoring tools, student enrollment management, quiz creation and grading, progress tracking, and certificate generation.",
    description: "Modern LMS for creating and delivering courses with RBAC and analytics.",
    blog: `<p>The Learning Management System required robust course delivery capabilities, comprehensive student tracking, and efficient grading tools. The implementation focused on performance optimization for larger cohorts, reliable quiz processing, and comprehensive reporting.</p><p>Key features include course authoring, enrollment management, automated quiz grading, progress tracking, and certificate generation.</p>`,
    techTags: ["Laravel", "PHP 8+", "MySQL", "Tailwind", "Livewire", "Docker"],
    technologies: ["Laravel", "PHP 8+", "MySQL", "Tailwind", "Livewire", "Docker"],
    image: "/images/lms.maffin.az/2.png",
    images: [
      "/images/lms.maffin.az/1.png",
      "/images/lms.maffin.az/2.png",
      "/images/lms.maffin.az/3.png",
      "/images/lms.maffin.az/4.png",
      "/images/lms.maffin.az/5.png",
      "/images/lms.maffin.az/6.png",
    ],
    demoUrl: "https://lms.maffin.az",
    featured: true,
    featuredOrder: 1,
    problem: "Needed a robust LMS with quizzes, grading, and progress tracking.",
    solution: "Implemented a modular Laravel architecture with RBAC, queues, and cached catalog queries.",
    impact: "Smooth student experience and maintainable admin workflows.",
    role: "Backend lead; collaborated with stakeholders on curriculum workflows.",
    metrics: [
      { label: "N+1 Queries", value: "Eliminated" },
      { label: "Scalability", value: "High" },
    ],
    personalNote: "I enjoyed tuning reporting queries for larger cohorts.",
    category: "Client Projects",
    status: "Ongoing",
    color: "from-blue-600 to-indigo-700",
    date: "2025 - Present",
    links: { demo: "https://lms.maffin.az", github: "#" },
    features: ["Course Authoring", "Enrollment Management", "Quiz System", "Certificate Generation"],
  },
  {
    id: 20,
    title: "Ofisait.az",
    subtitle: "Office Supplies E-commerce",
    client: "INCI",
    yearRange: "2025 – Present",
    shortDescription: "Office supplies e‑commerce with OpenCard + PHP + MySql backend.",
    longDescription: "Ofisait.az is an e-commerce platform specialized for office supplies, built with OpenCard, PHP and MySQL in a Docker environment. The system features product catalog management, order processing, inventory tracking, and customer account management with a focus on B2B workflows.",
    description: "Developed Ofisait.az backend for office solutions e‑commerce.",
    blog: `<p>Ofisait.az required a reliable e-commerce platform with B2B capabilities and consistent environments across development and production. The solution leveraged Laravel with MySQL in Docker containers for reproducible deployments.</p><p>Key features include comprehensive product catalog management, streamlined checkout for business accounts, and reliable order processing workflows.</p>`,
    techTags: ["OpenCard", "PHP", "MySql", "Docker"],
    technologies: ["OpenCard", "PHP", "MySql", "Docker"],
    image: "/images/ofisait.az/3.png",
    images: [
      "/images/ofisait.az/1.png",
      "/images/ofisait.az/2.png",
      "/images/ofisait.az/3.png",
      "/images/ofisait.az/4.png",
      "/images/ofisait.az/5.png",
    ],
    demoUrl: "https://ofisait.az",
    featured: true,
    featuredOrder: 4,
    problem: "Needed a reliable e‑commerce backend for office supplies with MySql.",
    solution: "Delivered a PHP + MySql stack with Docker for consistent environments.",
    impact: "Stable operations and maintainable codebase.",
    role: "Backend developer owning architecture and deployment.",
    metrics: [
      { label: "Uptime", value: "> 99.9%" },
      { label: "DB", value: "MySql" },
    ],
    personalNote: "I leaned on Docker to keep environments identical across machines.",
    category: "Client Projects",
    status: "Ongoing",
    color: "from-orange-500 to-red-600",
    date: "2025 - Present",
    links: { demo: "https://ofisait.az", github: "#" },
    features: ["Product Catalog", "Order Processing", "Inventory Management", "Business Accounts"],
  },
  {
    id: 21,
    title: "Chat2Desk.az",
    subtitle: "Unified Communication Tool",
    client: "INCI",
    yearRange: "2025 – Present",
    shortDescription: "Unified communication tool with Laravel backend and external APIs.",
    longDescription: "Chat2Desk.az is a unified communication platform that integrates multiple messaging channels into a single interface. Built with Laravel and MySQL, it connects to external messaging APIs, provides secure routing based on user roles, and streamlines support workflows for customer service teams.",
    description: "Integrated Chat2Desk.az with Laravel backend and external APIs for communication workflows.",
    blog: `<p>Chat2Desk.az needed to unify multiple communication channels and streamline support workflows for agents. The solution integrated external messaging APIs with reliable retry strategies and secure routing based on agent roles.</p><p>The platform centralizes messages from various sources, provides context for support agents, and enables efficient workflow management for customer inquiries.</p>`,
    techTags: ["Laravel", "PHP 8+", "MySQL"],
    technologies: ["Laravel", "PHP 8+", "MySQL"],
    image: "/images/chat2.maffin.az/1.png",
    images: [
      "/images/chat2.maffin.az/1.png",
      "/images/chat2.maffin.az/2.png",
      "/images/chat2.maffin.az/3.png",
      "/images/chat2.maffin.az/4.png",
      "/images/chat2.maffin.az/5.png",
      "/images/chat2.maffin.az/6.png",
    ],
    demoUrl: "https://chat2desk.az",
    featured: true,
    featuredOrder: 5,
    problem: "Teams needed a unified place for message routing and support workflows.",
    solution: "Built Laravel services integrating external APIs; implemented secure roles & workflows.",
    impact: "Cleaner comms and fewer manual steps for agents.",
    role: "Backend owner for integrations and secure routing.",
    metrics: [{ label: "Agent Efficiency", value: "+~20%" }],
    personalNote: "Integration reliability is everything—retry strategies paid off.",
    category: "Client Projects",
    status: "Ongoing",
    color: "from-purple-500 to-pink-600",
    date: "2025 - Present",
    links: { demo: "https://chat2desk.az", github: "#" },
    features: ["Channel Integration", "Message Routing", "Agent Workflows", "Customer Context"],
  },
  {
    id: 22,
    title: "HBNgroup.az",
    subtitle: "Enterprise Platform",
    client: "INCI",
    yearRange: "2025 – Present",
    shortDescription: "Enterprise platform with secure Laravel APIs and CI/CD pipelines.",
    longDescription: "HBNgroup.az is an enterprise-grade platform built with Laravel, PostgreSQL, and Docker. It features strict role-based access control, secure API endpoints, automated CI/CD pipelines, comprehensive monitoring, and strict database policies for data integrity and security.",
    description: "Backend developer for HBNgroup.az, delivering secure Laravel backend and pipelines.",
    blog: `<p>HBNgroup.az required a secure enterprise platform with automated deployment processes and strict access controls. The implementation focused on hardened security, reliable CI/CD pipelines, and comprehensive monitoring.</p><p>The system features strict role-based access control, secure API endpoints, automated testing in the CI/CD pipeline, and comprehensive audit logging for security compliance.</p>`,
    techTags: ["Laravel", "PHP 8+", "PostgreSQL", "Docker", "CI/CD"],
    technologies: ["Laravel", "PHP 8+", "PostgreSQL", "Docker", "CI/CD"],
    image: "/images/hbngroup.az/3.png",
    images: [
      "/images/hbngroup.az/1.png",
      "/images/hbngroup.az/2.png",
      "/images/hbngroup.az/3.png",
      "/images/hbngroup.az/4.png",
      "/images/hbngroup.az/5.png",
      "/images/hbngroup.az/6.png",
      "/images/hbngroup.az/7.png",
      "/images/hbngroup.az/8.png",
      "/images/hbngroup.az/9.png",
      "/images/hbngroup.az/10.png",
    ],
    demoUrl: "https://hbngroup.az",
    featured: false,
    featuredOrder: 10,
    problem: "Required secure APIs and automated deployments for enterprise teams.",
    solution: "Built strict RBAC, CI/CD, and monitoring; tightened database policies and migrations.",
    impact: "Confidence in releases and data security; faster cycle times.",
    role: "Backend developer focusing on security and delivery.",
    metrics: [
      { label: "Release Confidence", value: "High" },
      { label: "Security", value: "Hardened" },
    ],
    personalNote: "Loved bringing order and safety to a complex enterprise landscape.",
    category: "Client Projects",
    status: "Ongoing",
    color: "from-slate-700 to-slate-900",
    date: "2025 - Present",
    links: { demo: "https://hbngroup.az", github: "#" },
    features: ["Secure APIs", "Role-Based Access", "Automated CI/CD", "Enterprise Monitoring"],
  },
]

export function getProjects(): Project[] {
  return projects
}

export function getFeaturedProjects(): Project[] {
  return projects
      .filter((p) => p.featured)
      .sort((a, b) => (a.featuredOrder ?? 0) - (b.featuredOrder ?? 0))
}