import type { Project } from "@/types/project"

// Unified projects data: includes My Projects, Startups, and Client Projects.
// Contains fields required by Featured timeline (featured, featuredOrder) and Projects timeline (compat fields).
export const projects: Project[] = [
  // 🚀 My Projects
  {
    id: 1,
    title: "Passmate",
    client: "Personal Project",
    yearRange: "2024 – Present",
    shortDescription: "A privacy-first password manager with encryption, vaults, and cross-device sync.",
    longDescription: "Passmate is a secure password manager built with Laravel, React, and MySQL. It features end-to-end encryption, multiple vaults for password organization, and seamless cross-device synchronization through a Dockerized infrastructure. Designed as a practical cybersecurity-focused project for exploring encryption best practices and real-world data protection challenges.",
    techTags: ["Laravel", "React", "MySQL", "Tailwind", "Docker"],
    image: "/images/passmate/1.png",
    images: [
      "/images/passmate/1.png",
      "/images/passmate/2.png",
      "/images/passmate/3.png",
      "/images/passmate/4.png",
      "/images/passmate/5.png"
    ],
    demoUrl: "https://github.com/senanqulamov/PassMate",
    featured: true,
    featuredOrder: 2,
    problem: "Managing and syncing passwords securely across multiple devices while maintaining user privacy is complex and often dependent on third-party cloud providers.",
    solution: "Developed Passmate — a self-hosted password manager with encrypted local storage and secure synchronization. Designed the architecture using Laravel for backend APIs, React for a smooth interface, and Docker for reproducible environments.",
    impact: "Empowers users to take control of their password data without relying on external services. Enhances cybersecurity habits by promoting local encryption and user-managed vaults.",
    role: "Full-stack developer responsible for system architecture, encryption logic, frontend integration, and deployment pipeline.",
    metrics: [
      { label: "Encryption Strength", value: "AES-256" },
      { label: "Sync Speed", value: "< 1s local vault sync" },
      { label: "User Data Exposure", value: "0%" }
    ],
    personalNote: "I built Passmate to deepen my knowledge of encryption and security-oriented Laravel architectures. It’s both a portfolio project and a personal tool for secure credential management.",
    description: "A secure password manager with encryption, vault management, and cross-device sync built using Laravel and React.",
    date: "2024 - Present",
    category: "My Projects",
    status: "In Progress",
    links: { demo: "https://github.com/senanqulamov/PassMate", github: "https://github.com/senanqulamov/PassMate" },
  },
  {
    id: 2,
    title: "SchoolExam",
    subtitle: "Exam & Quiz Platform",
    shortDescription: "An online platform for creating and managing school exams, quizzes, and results.",
    description: "Exam & quiz system with auto-grading and analytics.",
    blog: `<p>SchoolExam is an exam and quiz system built with Laravel, Inertia.js, and MySQL. It enables teachers to create exams, auto-grade answers, and provides performance reports for students.</p>`,
    image: "/images/schoolexam/1.jpg",
    images: [
      "/images/schoolexam/1.jpg",
      "/images/schoolexam/2.jpg",
      "/images/schoolexam/3.jpg",
      "/images/schoolexam/4.jpg",
      "/images/schoolexam/5.jpg",
    ],
    technologies: ["Laravel", "Inertia.js", "Vue.js", "MySQL"],
    category: "My Projects",
    status: "Completed",
    color: "from-blue-400 to-green-400",
    date: "2023",
    links: { demo: "#", github: "#" },
    features: ["Exam Creation", "Auto-grading", "Student Reports", "Analytics Dashboard"],
    featured: false,
  },
  {
    id: 3,
    title: "JavaLearningApp",
    subtitle: "Interactive Java Study Tool",
    shortDescription: "Practice Java with coding challenges and quizzes.",
    description: "A study tool for Java concepts with practical challenges.",
    blog: `<p>JavaLearningApp helps users practice Java through exercises and mini-projects. Built with JavaFX, Javalin APIs, and MySQL backend.</p>`,
    image: "/images/javalearningapp/1.jpg",
    images: [
      "/images/javalearningapp/1.jpg",
      "/images/javalearningapp/2.jpg",
      "/images/javalearningapp/3.jpg",
      "/images/javalearningapp/4.jpg",
      "/images/javalearningapp/5.jpg",
    ],
    technologies: ["Java", "Javalin", "JavaFX", "MySQL"],
    category: "My Projects",
    status: "In Progress",
    color: "from-yellow-400 to-red-400",
    date: "2024 - Present",
    links: { demo: "#", github: "#" },
    features: ["Java Quizzes", "Coding Challenges", "API Integration", "Progress Tracking"],
    featured: false,
  },
  {
    id: 4,
    title: "MoneyBadge",
    subtitle: "Gamified Productivity Tool",
    shortDescription: "Gamified task management with badges and progress.",
    description: "Gamification app awarding badges for productivity.",
    blog: `<p>MonayBadge combines task management with gamification. Users earn badges for consistency and progress. Built with Laravel, React, and Tailwind.</p>`,
    image: "/images/monaybadge/1.jpg",
    images: [
      "/images/monaybadge/1.jpg",
      "/images/monaybadge/2.jpg",
      "/images/monaybadge/3.jpg",
      "/images/monaybadge/4.jpg",
      "/images/monaybadge/5.jpg",
    ],
    technologies: ["Laravel", "React", "MySQL", "Tailwind"],
    category: "My Projects",
    status: "Prototype",
    color: "from-pink-400 to-orange-400",
    date: "2023",
    links: { demo: "#", github: "#" },
    features: ["Badge Rewards", "Task Tracking", "Leaderboard", "User Profiles"],
    featured: false,
  },
  {
    id: 5,
    title: "CustomAdmin",
    subtitle: "Universal Admin Panel",
    shortDescription: "Customizable admin for multiple startups with dynamic CRUD.",
    description: "Universal admin panel for multiple projects with context switching.",
    blog: `<p>CustomAdmin is a universal admin panel designed to support multiple startups (NeoSphere, BidBary, BorderMate). Built with Laravel + Next.js, it allows project/data context switching, translation management, and dynamic CRUD.</p>`,
    image: "/images/customadmin/1.jpg",
    images: [
      "/images/customadmin/1.jpg",
      "/images/customadmin/2.jpg",
      "/images/customadmin/3.jpg",
      "/images/customadmin/4.jpg",
      "/images/customadmin/5.jpg",
    ],
    technologies: ["Laravel", "Next.js", "Tailwind", "MySQL"],
    category: "My Projects",
    status: "In Development",
    color: "from-teal-400 to-blue-500",
    date: "2024 - Present",
    links: { demo: "#", github: "#" },
    features: ["User Management", "CRUD Tables", "Translation Management", "Settings Panel"],
    featured: false,
  },

  // 🚀 Startups
  {
    id: 6,
    title: "NeoSphere",
    subtitle: "Union Hub & Gig Marketplace",
    shortDescription: "Next-gen platform for Spheres, Core Hubs, Karma Points, jobs, and events.",
    description: "Hybrid gig marketplace and networking hub connecting people, communities, and opportunities.",
    blog: `<p>NeoSphere is a hybrid gig marketplace and networking hub designed to connect people with opportunities, communities, and growth. Users can explore job boards, attend events, and build reputation through a karma-based system. Organizations can create sponsored Spheres, while Core Hubs provide structure and governance. Tech stack: Laravel (backend), React (frontend), MySQL.</p>`,
    image: "/images/neosphere/1.png",
    images: [
      "/images/neosphere/1.jpg",
      "/images/neosphere/2.jpg",
      "/images/neosphere/3.jpg",
      "/images/neosphere/4.jpg",
      "/images/neosphere/5.jpg",
    ],
    technologies: ["Laravel", "React", "MySQL"],
    category: "Startups",
    status: "MVP",
    color: "from-primary to-accent",
    date: "2023 - Present",
    links: { demo: "#", github: "#" },
    features: [
      "Job Marketplace",
      "Event Discovery & Hosting",
      "Karma Reputation System",
      "Sponsored & Community Spheres",
    ],
    featured: false,
  },
  {
    id: 7,
    title: "BidBary",
    subtitle: "Collectors & Auction App",
    shortDescription: "Modern auction marketplace with live bidding and collector engagement.",
    description: "Auction platform with live bidding, profiles, and transparent flows.",
    blog: `<p>BidBary redefines the auction experience for collectors and sellers. With live bidding, collector profiles, auction history, and a modern UI designed with Motiff, it creates a transparent and engaging platform for rare items and collectibles.</p>`,
    image: "/images/bidbary/1.png",
    images: [
      "/images/bidbary/1.png",
      "/images/bidbary/2.png",
      "/images/bidbary/3.png",
      "/images/bidbary/4.png",
      "/images/bidbary/5.png",
    ],
    technologies: ["Java", "Javalin", "Next.js", "Tailwind"],
    category: "Startups",
    status: "In Development",
    color: "from-purple-400 to-pink-400",
    date: "2024 - Present",
    links: { demo: "#", github: "#" },
    features: ["Real-time Bidding", "Collector Profiles", "Auction History", "Modern Dark UI"],
    featured: false,
  },
  {
    id: 8,
    title: "BorderMate",
    subtitle: "Travel & Border Crossing Assistant",
    shortDescription: "Assist travelers with documents, customs info, and real-time border updates.",
    description: "Helps travelers with cross-border logistics and live updates.",
    blog: `<p>BorderMate helps travelers with cross-border logistics. Features include document storage, customs information, and live updates about checkpoints.</p>`,
    image: "/images/bordermate/1.jpg",
    images: [
      "/images/bordermate/1.jpg",
      "/images/bordermate/2.jpg",
      "/images/bordermate/3.jpg",
      "/images/bordermate/4.jpg",
      "/images/bordermate/5.jpg",
    ],
    technologies: ["React Native", "Laravel", "MySQL", "REST APIs"],
    category: "Startups",
    status: "Prototype",
    color: "from-green-400 to-blue-400",
    date: "2024",
    links: { demo: "#", github: "#" },
    features: ["Travel Docs", "Customs Info", "Live Border Updates", "Journey Planner"],
    featured: false,
  },
  {
    id: 9,
    title: "Allrent.io",
    subtitle: "Online Rental Marketplace",
    shortDescription: "Rental marketplace with payments, maps, and custom booking.",
    description: "Modern rental platform with payments, reviews, maps, and reservations.",
    blog: `<p>Allrent.io is a modern rental platform I built from the ground up, initially as a freelancer and later as the company’s technical lead. It features online payments, review systems, interactive maps, and a custom reservation calendar. Stack: Laravel, React, MySQL.</p>`,
    image: "/images/allrent/1.jpg",
    images: [
      "/images/allrent/1.jpg",
      "/images/allrent/2.jpg",
      "/images/allrent/3.jpg",
      "/images/allrent/4.jpg",
      "/images/allrent/5.jpg",
    ],
    technologies: ["Laravel", "React", "MySQL", "Bootstrap"],
    category: "Startups",
    status: "Completed",
    color: "from-yellow-400 to-orange-500",
    date: "2022 - 2023",
    links: { demo: "#", github: "#" },
    features: ["Online Payments", "Interactive Maps", "Custom Reservation Calendar", "Review System"],
    featured: false,
  },

  // 🏢 Client Projects (merged with case study data and featured flags)
  {
    id: 12,
    title: "Otomall.az",
    client: "FerrumCapital",
    shortDescription: "Scalable Laravel + React platform with payments and secure backend.",
    description: "Developed and maintained Otomall.az with Laravel and React, ensuring scalability, payments integration, and secure backend systems.",
    image: "/images/otomall.az/8.png",
    images: [
      "/images/otomall.az/1.png",
      "/images/otomall.az/2.png",
      "/images/otomall.az/3.png",
      "/images/otomall.az/4.png",
      "/images/otomall.az/5.png",
      "/images/otomall.az/6.png",
      "/images/otomall.az/7.png",
    ],
    technologies: ["Laravel", "React", "MySQL", "Bootstrap"],
    category: "Client Projects",
    status: "Completed",
    color: "from-red-400 to-orange-400",
    date: "2021 - 2022",
    links: { demo: "#", github: "#" },
    features: ["Corporate Website", "Payments", "Security Features", "Responsive UI"],
    featured: false,
  },
  {
    id: 10,
    title: "Agagroup.az",
    client: "FerrumCapital",
    yearRange: "2021 – 2022",
    shortDescription: "Corporate site and backend services with secure CMS and optimized backend.",
    longDescription: undefined,
    techTags: ["PHP", "WordPress", "MySQL", "Bootstrap"],
    image: "/images/agagroup.az/5.png",
    images: [
      "/images/agagroup.az/1.png",
      "/images/agagroup.az/2.png",
      "/images/agagroup.az/3.png",
      "/images/agagroup.az/4.png",
      "/images/agagroup.az/5.png",
      "/images/agagroup.az/6.png",
    ],
    demoUrl: "https://agagroup.az",
    featured: true,
    featuredOrder: 5,
    problem: "Agagroup needed a performant corporate website with a secure CMS for non-technical editors.",
    solution: "Delivered a custom WordPress build with hardened security, reusable blocks, and optimized MySQL queries.",
    impact: "Reduced content publishing time by 60%. Improved Lighthouse performance into the green range.",
    role: "Full‑stack developer responsible for architecture, theme development, and deployment.",
    metrics: [
      { label: "TTFB", value: "< 200ms" },
      { label: "Core Web Vitals", value: "Green" },
      { label: "Editor Effort", value: "-60%" },
    ],
    personalNote: "I focused on editor experience and security hardening while keeping the site blazing fast.",
    description: "Delivered corporate site and backend services for Agagroup.az with PHP and MySQL.",
    date: "2021 - 2022",
    category: "Client Projects",
    status: "Completed",
    links: { demo: "https://agagroup.az", github: "#" },
  },
  {
    id: 11,
    title: "Balli.az",
    client: "FerrumCapital",
    yearRange: "2021 – 2022",
    shortDescription: "E‑commerce with secure payments and reliable order workflows.",
    techTags: ["PHP", "WordPress", "MySQL", "REST APIs", "Stripe"],
    image: "/images/balli.az/demo1.png",
    images: [
      "/images/balli.az/demo1.png",
      "/images/balli.az/demo2.png",
      "/images/balli.az/demo3.png",
      "/images/balli.az/demo4.png",
      "/images/balli.az/demo5.png",
    ],
    demoUrl: "https://balli.az",
    featured: false,
    featuredOrder: 2,
    problem: "Checkout friction and slow product pages were hurting conversions.",
    solution: "Optimized product queries, implemented Stripe payments, and streamlined the checkout UX.",
    impact: "Checkout completion rate increased by ~18%. Product page LCP improved by ~35%.",
    role: "Backend and integration lead; collaborated on frontend performance fixes.",
    metrics: [
      { label: "Checkout Conversion", value: "+18%" },
      { label: "LCP", value: "-35%" },
    ],
    personalNote: "Balancing reliability and speed across checkout flows was an exciting challenge.",
    description: "Built Balli.az with PHP backend and WordPress, integrating secure payment systems and optimized APIs.",
    date: "2021 - 2022",
    category: "Client Projects",
    status: "Completed",
    links: { demo: "https://balli.az", github: "#" },
  },
  {
    id: 14,
    title: "Shiplounge.co",
    client: "Deirvlon Technologies",
    yearRange: "2022",
    shortDescription: "End‑to‑end cargo and logistics platform for SMEs.",
    techTags: ["Laravel", "MySQL", "Bootstrap"],
    image: "/images/shiplounge.co/7.png",
    images: [
      "/images/shiplounge.co/1.png",
      "/images/shiplounge.co/2.png",
      "/images/shiplounge.co/3.png",
      "/images/shiplounge.co/4.png",
      "/images/shiplounge.co/5.png",
      "/images/shiplounge.co/6.png",
      "/images/shiplounge.co/7.png",
      "/images/shiplounge.co/8.png",
      "/images/shiplounge.co/9.png",
    ],
    demoUrl: "https://shiplounge.co",
    featured: false,
    featuredOrder: 3,
    problem: "Operators needed a reliable tool to manage shipments, tariffs, and invoicing without performance bottlenecks.",
    solution: "Designed a Laravel architecture with queues, caching, and indexed queries; built ops‑friendly UIs.",
    impact: "Reduced ops errors and improved processing speed; clear visibility via dashboards.",
    role: "Backend lead and UI architect for operations workflows.",
    metrics: [
      { label: "N+1 Queries", value: "Eliminated" },
      { label: "Bulk Ops Speed", value: "+~2x" },
    ],
    personalNote: "The most rewarding part was seeing operators handle complex workflows with fewer clicks.",
    description: "Logistics and cargo management system with tariffs, tracking, invoicing, and RBAC.",
    date: "2022",
    category: "Client Projects",
    status: "Completed",
    links: { demo: "https://shiplounge.co", github: "#" },
  },
  {
    id: 16,
    title: "LuckyHolidays.az",
    client: "GlobalSoft",
    yearRange: "2025",
    shortDescription: "Travel booking platform with payments and optimized APIs.",
    techTags: ["Laravel", "PHP", "MySQL", "React", "Node.js"],
    image: "/images/luckyholidays.az/5.png",
    images: [
      "/images/luckyholidays.az/1.png",
      "/images/luckyholidays.az/2.png",
      "/images/luckyholidays.az/3.png",
      "/images/luckyholidays.az/4.png",
      "/images/luckyholidays.az/5.png",
      "/images/luckyholidays.az/6.png",
      "/images/luckyholidays.az/7.png",
      "/images/luckyholidays.az/8.png",
    ],
    demoUrl: "https://luckyholidays.az",
    featured: false,
    featuredOrder: 4,
    problem: "Travel site needed robust booking flows, payments, and fast catalog browsing.",
    solution: "Built Laravel APIs with pagination/caching; integrated payments; delivered responsive React UI.",
    impact: "Faster browsing and fewer checkout drop‑offs; maintainable admin tooling.",
    role: "Full‑stack contributor across backend APIs and frontend performance.",
    metrics: [
      { label: "Catalog TTI", value: "-30%" },
      { label: "Checkout Errors", value: "-40%" },
    ],
    personalNote: "We prioritized perceived performance and a clean admin experience.",
    description: "Developed LuckyHolidays.az for travel services, focusing on Laravel backend and secure APIs.",
    date: "2025",
    category: "Client Projects",
    status: "Completed",
    links: { demo: "https://luckyholidays.az", github: "#" },
  },
  {
    id: 17,
    title: "CTSA.az",
    client: "GlobalSoft",
    yearRange: "2025",
    shortDescription: "Enterprise solutions with Laravel backend and React frontend.",
    techTags: ["Laravel", "PHP", "MySQL", "Gitlab CI/CD", "React", "Node.js"],
    image: "/images/ctsa.az/1.png",
    images: [
      "/images/ctsa.az/1.png",
      "/images/ctsa.az/2.png",
      "/images/ctsa.az/3.png",
      "/images/ctsa.az/4.png",
      "/images/ctsa.az/5.png",
      "/images/ctsa.az/6.png",
    ],
    demoUrl: "https://ctsa.az",
    featured: false,
    featuredOrder: 5,
    problem: "Needed a secure enterprise platform with multiple integrations and CI/CD.",
    solution: "Implemented RBAC, API integrations, and GitLab CI/CD; hardened security and audit trails.",
    impact: "Reliable deployments and improved developer velocity; stronger security posture.",
    role: "Backend developer leading integrations and CI/CD pipelines.",
    metrics: [
      { label: "Deploy Time", value: "-50%" },
      { label: "Incidents", value: "↓" },
    ],
    personalNote: "Setting up pipelines that the team trusts is always worth the effort.",
    description: "Built CTSA.az backend services with Laravel + React, integrating APIs and security.",
    date: "2025",
    category: "Client Projects",
    status: "Completed",
    links: { demo: "https://ctsa.az", github: "#" },
  },
  {
    id: 18,
    title: "GPSAI.az",
    client: "INCI",
    yearRange: "2025",
    shortDescription: "GPS tracking and AI‑enhanced telemetry with a custom admin panel.",
    techTags: ["Laravel", "Javalin", "PHP 8+", "MySQL/PostgreSQL"],
    image: "/images/gpsai.az/4.png",
    images: [
      "/images/gpsai.az/1.png",
      "/images/gpsai.az/2.png",
      "/images/gpsai.az/3.png",
      "/images/gpsai.az/4.png",
    ],
    demoUrl: "https://gpsai.az",
    featured: false,
    featuredOrder: 6,
    problem: "Telemetry workloads demanded scalable APIs and a clear operator UI.",
    solution: "Built Laravel APIs and a custom admin panel; optimized hot reads and background jobs.",
    impact: "Stable operations with low latency; clean admin for day‑to‑day tasks.",
    role: "Backend engineer and admin panel author.",
    metrics: [
      { label: "API Latency", value: "Low" },
      { label: "Admin Tasks", value: "Streamlined" },
    ],
    personalNote: "Telemetry is all about well‑indexed reads and reliable workers.",
    description: "Developed GPSAI.az backend with Laravel and Javalin; built custom AdminPanel for landing.",
    date: "2025",
    category: "Client Projects",
    status: "Completed",
    links: { demo: "https://gpsai.az", github: "#" },
  },
  {
    id: 19,
    title: "LMS",
    client: "INCI",
    yearRange: "2025 – Present",
    shortDescription: "Learning management system with authoring, enrollments, quizzes, and certificates.",
    techTags: ["Laravel", "PHP 8+", "MySQL", "Tailwind", "Livewire", "Docker"],
    image: "/images/lms.maffin.az/2.png",
    images: [
      "/images/lms.maffin.az/1.png",
      "/images/lms.maffin.az/2.png",
      "/images/lms.maffin.az/3.png",
      "/images/lms.maffin.az/4.png",
      "/images/lms.maffin.az/5.png",
      "/images/lms.maffin.az/6.png",
    ],
    demoUrl: "https://lms.maffin.az",
    featured: true,
    featuredOrder: 1,
    problem: "Needed a robust LMS with quizzes, grading, and progress tracking.",
    solution: "Implemented a modular Laravel architecture with RBAC, queues, and cached catalog queries.",
    impact: "Smooth student experience and maintainable admin workflows.",
    role: "Backend lead; collaborated with stakeholders on curriculum workflows.",
    metrics: [
      { label: "N+1 Queries", value: "Eliminated" },
      { label: "Scalability", value: "High" },
    ],
    personalNote: "I enjoyed tuning reporting queries for larger cohorts.",
    description: "Modern LMS for creating and delivering courses with RBAC and analytics.",
    date: "2025 - Present",
    category: "Client Projects",
    status: "Ongoing",
    links: { demo: "https://lms.maffin.az", github: "#" },
  },
  {
    id: 20,
    title: "Ofisait.az",
    client: "INCI",
    yearRange: "2025 – Present",
    shortDescription: "Office supplies e‑commerce with OpenCard + PHP + MySql backend.",
    techTags: ["Laravel", "MySql", "Docker"],
    image: "/images/ofisait.az/3.png",
    images: [
      "/images/ofisait.az/1.png",
      "/images/ofisait.az/2.png",
      "/images/ofisait.az/3.png",
      "/images/ofisait.az/4.png",
      "/images/ofisait.az/5.png",
    ],
    demoUrl: "https://ofisait.az",
    featured: true,
    featuredOrder: 3,
    problem: "Needed a reliable e‑commerce backend for office supplies with MySql.",
    solution: "Delivered a PHP + MySql stack with Docker for consistent environments.",
    impact: "Stable operations and maintainable codebase.",
    role: "Backend developer owning architecture and deployment.",
    metrics: [
      { label: "Uptime", value: "> 99.9%" },
      { label: "DB", value: "MySql" },
    ],
    personalNote: "I leaned on Docker to keep environments identical across machines.",
    description: "Developed Ofisait.az backend for office solutions e‑commerce.",
    date: "2025 - Present",
    category: "Client Projects",
    status: "Ongoing",
    links: { demo: "https://ofisait.az", github: "#" },
  },
  {
    id: 21,
    title: "Chat2Desk.az",
    client: "INCI",
    yearRange: "2025 – Present",
    shortDescription: "Unified communication tool with Laravel backend and external APIs.",
    techTags: ["Laravel", "PHP 8+", "MySQL"],
    image: "/images/chat2.maffin.az/1.png",
    images: [
      "/images/chat2.maffin.az/1.png",
      "/images/chat2.maffin.az/2.png",
      "/images/chat2.maffin.az/3.png",
      "/images/chat2.maffin.az/4.png",
      "/images/chat2.maffin.az/5.png",
      "/images/chat2.maffin.az/6.png",
    ],
    demoUrl: "https://chat2desk.az",
    featured: true,
    featuredOrder: 4,
    problem: "Teams needed a unified place for message routing and support workflows.",
    solution: "Built Laravel services integrating external APIs; implemented secure roles & workflows.",
    impact: "Cleaner comms and fewer manual steps for agents.",
    role: "Backend owner for integrations and secure routing.",
    metrics: [{ label: "Agent Efficiency", value: "+~20%" }],
    personalNote: "Integration reliability is everything—retry strategies paid off.",
    description: "Integrated Chat2Desk.az with Laravel backend and external APIs for communication workflows.",
    date: "2025 - Present",
    category: "Client Projects",
    status: "Ongoing",
    links: { demo: "https://chat2desk.az", github: "#" },
  },
  {
    id: 22,
    title: "HBNgroup.az",
    client: "INCI",
    yearRange: "2025 – Present",
    shortDescription: "Enterprise platform with secure Laravel APIs and CI/CD pipelines.",
    techTags: ["Laravel", "PHP 8+", "PostgreSQL", "Docker", "CI/CD"],
    image: "/images/hbngroup.az/3.png",
    images: [
      "/images/hbngroup.az/1.png",
      "/images/hbngroup.az/2.png",
      "/images/hbngroup.az/3.png",
      "/images/hbngroup.az/4.png",
      "/images/hbngroup.az/5.png",
      "/images/hbngroup.az/6.png",
      "/images/hbngroup.az/7.png",
      "/images/hbngroup.az/8.png",
      "/images/hbngroup.az/9.png",
      "/images/hbngroup.az/10.png",
    ],
    demoUrl: "https://hbngroup.az",
    featured: false,
    featuredOrder: 10,
    problem: "Required secure APIs and automated deployments for enterprise teams.",
    solution: "Built strict RBAC, CI/CD, and monitoring; tightened database policies and migrations.",
    impact: "Confidence in releases and data security; faster cycle times.",
    role: "Backend developer focusing on security and delivery.",
    metrics: [
      { label: "Release Confidence", value: "High" },
      { label: "Security", value: "Hardened" },
    ],
    personalNote: "Loved bringing order and safety to a complex enterprise landscape.",
    description: "Backend developer for HBNgroup.az, delivering secure Laravel backend and pipelines.",
    date: "2025 - Present",
    category: "Client Projects",
    status: "Ongoing",
    links: { demo: "https://hbngroup.az", github: "#" },
  },
]

export function getProjects(): Project[] {
  return projects
}

export function getFeaturedProjects(): Project[] {
  return projects
    .filter((p) => p.featured)
    .sort((a, b) => (a.featuredOrder ?? 0) - (b.featuredOrder ?? 0))
}

